---
groups:
  - name: concourse-ruby
    jobs:
      - (( append ))
      - 'build-concourse-ruby:2.3'
      - 'promote-concourse-ruby:2.3'

resources:
  - name: 'concourse-ruby:2.3 @github'
    .: (( inject meta.resources.dockerfiles ))
    source:
      paths:
        - concourse-ruby/2.3/Dockerfile
  - name: 'concourse-ruby:2.3-rc @dockerhub'
    .: (( inject meta.resources.dockerhub ))
    source:
      repository: (( concat meta.dockerhub.account "/concourse-ruby" ))
      tag: 2.3-rc
  - name: 'concourse-ruby:2.3 @dockerhub'
    .: (( inject meta.resources.dockerhub ))
    source:
      repository: (( concat meta.dockerhub.account "/concourse-ruby" ))
      tag: 2.3

jobs:
  - name: 'build-concourse-ruby:2.3'
    public: true
    plan:
      - aggregate:
        - get: git
          resource: 'concourse-ruby:2.3 @github'
          trigger:  true
        - { get: img, resource: 'concourse:latest @dockerhub', trigger: true, passed: ['promote-concourse:latest'] }
      - put: 'concourse-ruby:2.3-rc @dockerhub'
        params:
          build: git/concourse-ruby/2.3
  - name: 'promote-concourse-ruby:2.3'
    public: true
    plan:
      - get: rc
        resource: 'concourse-ruby:2.3-rc @dockerhub'
        passed: ['build-concourse-ruby:2.3']
        params: { save: true }
      - put: 'concourse-ruby:2.3 @dockerhub'
        params:
          load: rc
