---
groups:
  - name: concourse-ruby
    jobs:
      - (( append ))
      - 'bump-ruby-versions'

resources:
  - name: 'ruby-buildpack'
    .: (( inject meta.resources.github-release ))
    source:
      owner: cloudfoundry
      repository: ruby-buildpack

  - name: git
    .: (( inject meta.resources.dockerfiles ))

jobs:
  - name: 'bump-ruby-versions'
    public: true
    plan:
      - { get: git }
      - { get: buildpack, resource: 'ruby-buildpack', trigger: true }
      - task: bump
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: starkandwayne/concourse
              tag: latest
          inputs:
          - name: git
          - name: buildpack
          outputs:
          - name: pushme
          run:
            path: git/ci/scripts/update-dockerfile-from-buildpack-resources.sh
          params:
            buildpack: buildpack/ruby-buildpack-cflinuxfs3-*.zip
            dependency: ruby
            dockerfile_dep_prefix: RUBY
            git_email: (( grab meta.git.email ))
            git_name:  (( grab meta.git.name ))
      - put: git
        params:
          rebase: true
          repository: pushme
