---
groups:
  - name: concourse-kubernetes
    jobs:
      - (( append ))
      - 'build-concourse-kubernetes:latest'

resources:
  - name: 'concourse-kubernetes:latest @github'
    .: (( inject meta.resources.dockerfiles ))
    source:
      paths:
        - concourse-kubernetes/latest/Dockerfile
        - concourse-kubernetes/latest/scripts/*

  - name: 'concourse-kubernetes:latest @dockerhub'
    .: (( inject meta.resources.dockerhub ))
    source:
      repository: (( concat meta.dockerhub.account "/concourse" ))
      tag: latest

jobs:
  - name: 'build-concourse-kubernetes:latest'
    public: true
    plan:
      - get: git
        resource: 'concourse-kubernetes:latest @github'
        trigger:  true
      - put: 'concourse-kubernetes:latest @dockerhub'
        params:
          build: git/concourse-kubernetes/latest
