---
groups:
  - name: concourse
    jobs:
      - (( append ))
      - 'build-concourse:latest'

resources:
  - name: 'concourse:latest @github'
    .: (( inject meta.resources.dockerfiles ))
    source:
      paths:
        - concourse/latest/Dockerfile
        - concourse/latest/scripts/*

  - name: 'concourse:latest @dockerhub'
    .: (( inject meta.resources.dockerhub ))
    source:
      repository: (( concat meta.dockerhub.account "/concourse" ))
      tag: latest

jobs:
  - name: 'build-concourse:latest'
    public: true
    plan:
      - get: git
        resource: 'concourse:latest @github'
        trigger:  true
      - put: 'concourse:latest @dockerhub'
        params:
          build: git/concourse/latest
