---
groups:
  - name: concourse-java
    jobs:
      - (( append ))
      - 'build-concourse-java:8'

resources:
  - name: 'concourse-java:8 @github'
    .: (( inject meta.resources.dockerfiles ))
    source:
      paths:
        - concourse-java/8/Dockerfile
  - name: 'concourse-java:8 @dockerhub'
    .: (( inject meta.resources.dockerhub ))
    source:
      repository: (( concat meta.dockerhub.account "/concourse-java" ))
      tag: "8"

jobs:
  - name: 'build-concourse-java:8'
    public: true
    plan:
      - { get: git, resource: 'concourse-java:8 @github',    trigger: true }
      - { get: img, resource: 'concourse:latest @dockerhub', trigger: true, passed: ['build-concourse:latest'], params: {skip_download: true} }
      - put: 'concourse-java:8 @dockerhub'
        params:
          build: git/concourse-java/8
          tag_as_latest: true
