---
meta:
  dockerhub:
    account:  starkandwayne
    email:    (( vault "secret/pipelines/dockerfiles/dockerhub:email" ))
    username: (( vault "secret/pipelines/dockerfiles/dockerhub:username" ))
    password: (( vault "secret/pipelines/dockerfiles/dockerhub:password" ))

  gcr: # Google Container Registry
    account: gcr.io/starkandwayne-registry/gcp-cloudshell
    username: _json_key
    password: (( vault "secret/pipelines/dockerfiles/gcr:service_account_key" ))

  github:
    key: (( vault "secret/pipelines/shared/github:private_key" ))

  resources:
    dockerfiles:
      type: git
      source:
        uri: git@github.com:starkandwayne/dockerfiles
        branch: master
        private_key: (( grab meta.github.key ))

    gcr:
      type: docker-image
      source:
        username: (( grab meta.gcr.username ))
        password: (( grab meta.gcr.password ))

    dockerhub:
      type: docker-image
      source:
        email:    (( grab meta.dockerhub.email ))
        username: (( grab meta.dockerhub.username ))
        password: (( grab meta.dockerhub.password ))

groups:
  - name: '*'
    jobs: (( grab groups.concourse.jobs groups.concourse-go.jobs groups.concourse-java.jobs groups.concourse-ruby.jobs groups.concourse-nodejs.jobs groups.concourse-kubernetes.jobs groups.gcp-cloudshell.jobs ))
  - name: concourse
  - name: concourse-go
  - name: concourse-java
  - name: concourse-ruby
  - name: concourse-nodejs
  - name: concourse-kubernetes
  - name: gcp-cloudshell
