groups:
  - name: concourse-go
    jobs: 
      - 'build concourse-go:1.4'
      - 'promote concourse-go:1.4'

resources:
  - name: 'concourse-go:1.4 @github'
    .: (( inject meta.resources.dockerfiles ))
    source:
      paths:
        - concourse-go/1.4/Dockerfile
  - name: 'concourse-go:1.4-rc @dockerhub'
    .: (( inject meta.resources.dockerhub ))
    source:
      repository: (( concat meta.dockerhub.account "/concourse-go" ))
      tag: 1.4-rc
  - name: 'concourse-go:1.4 @dockerhub'
    .: (( inject meta.resources.dockerhub ))
    source:
      repository: (( concat meta.dockerhub.account "/concourse-go" ))
      tag: 1.4

jobs:
  - name: 'build concourse-go:1.4'
    public: true
    plan:
      - aggregate:
        - { get: git, resource: 'concourse-go:1.4 @github',    trigger:  true }
        - { get: img, resource: 'concourse:latest @dockerhub', trigger: true }
      - put: 'concourse-go:1.4-rc @dockerhub'
        params: { build: git/concourse-go/1.4 }
  - name: 'promote concourse-go:1.4'
    public: true
    plan:
      - get: rc
        resource: 'concourse-go:1.4-rc @dockerhub'
        passed: ['build concourse-go:1.4']
      - put: 'concourse-go:1.4 @dockerhub'
        params:
          load_base:       rc
          load_file:       rc/image
          load_repository: (( concat meta.dockerhub.account "/concourse-go" ))
          load_tag:        1.4-rc
